principal = float(input("Enter Principal Amount : "))
time = int(input("Enter Time duration in years : "))
rate = int(input("Enter Rate of Interest(in %) : "))
print("Simple Interest :", (principal*time*rate)/100)
# print("Simple Interest for the principal amount :", principal, " With :", rate, "% of Rate for ", time, "Years of time is : ", simpleInterest)